name: Build and Deploy Python App

on:
  push:
    branches:
      - main  # Change to master if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies into package
      run: |
        python -m pip install --upgrade pip
        pip install --target=".python_packages/lib/site-packages" -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'xxxthethingxxx'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
